//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitcoinDeveloper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BitcoinTransactionEntities : DbContext
    {
        public BitcoinTransactionEntities()
            : base("name=BitcoinTransactionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Exchange> Exchanges { get; set; }
        public virtual DbSet<ExchangeCurrency> ExchangeCurrencies { get; set; }
        public virtual DbSet<ExchangeType> ExchangeTypes { get; set; }
        public virtual DbSet<Execution> Executions { get; set; }
        public virtual DbSet<ExecutionsAccount> ExecutionsAccounts { get; set; }
        public virtual DbSet<FundsBalance> FundsBalances { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<TransactionConfirmed> TransactionConfirmeds { get; set; }
        public virtual DbSet<TransactionRecord> TransactionRecords { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
